config/routes.rb
ZikaronBasalon::Application.routes.draw do
  post 'webhook', :to => 'webhooks#webhook'

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/  do

    # Add support for Mailpreview
    if Rails.env.development?
      mount MailPreview => 'mail_view'
    end

    get 'my-profile', :to => 'users#profile'

    devise_for :users, controllers: { registrations: "registrations" } do
      get '/users/sign_out' => 'devise/sessions#destroy'
    end

    resources :managers do
      post :remove_city, on: :member
      get :export_hosts, on: :member
      get :export_witnesses, on: :member
      get :export_guests, on: :member
    end


    resources :regions do
      member do
        put :add_city
        get :remove_city
      end
    end

    resources :guests
    resources :sessions, only: [:new, :create]
    resources :users, only: [:new] do
      put :assignrole, on: :member
    end
    resources :witnesses do
      get :assign, on: :member
      get :unassign, on: :member
      resources :comments
    end
    
    match 'signup', :to => 'users#new', as: :signup
    
    resources :hosts do
      resources :comments
    end

    resources :invites, only: [:create, :update, :destroy]

    match "pages/home", :to => 'pages#home', as: :host_search
    match "pages/host_register_link", :to => 'pages#host_register_link', as: :host_register_link
    get "pages/privacy_policy"
    get "pages/welcome"
    root :to => 'pages#welcome'
  end
end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :name, :region_id, :community_leaderships_count

  belongs_to :region
  has_many :community_leaderships
  has_many :managers, :through => :community_leaderships
  has_many :hosts
  has_many :witnesses

  def self.without_managers
  	cities = []
  	City.all.each do |c|
  		cities.push(c) if c.community_leaderships_count === 0
  	end
  	cities
  end

  def self.without_anyone
    cities = []
    City.all.each do |c|
      cities.push(c) if c.managers.empty? && c.hosts.empty? && c.witnesses.empty?
    end
    cities
  end
end

app/helpers/cities_helper.rb
module CitiesHelper

  def filter_cities(cities, country_id, region_id)
    if region_id.present?
      cities = cities.where(region_id: region_id)
    elsif country_id.present?
      region_ids = Region.where(country_id: country_id).pluck(:id)
      cities = cities.where(region_id: region_ids)
    end
    return cities
  end

end

app/views/cities/edit.html.erb
<% title "#{@city.name}" %>


<div id="edit_host_container">
  <%= form_for @city, html: {class: "form-horizontal"} do |f| %>
     <div class="control-group">
        <%= f.label :name, "שם", class: "control-label" %>
        <div class="controls">
          <%= f.text_field :name %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :manager_email, "Manager Email", class: "control-label" %>
        <div class="controls">
          <%= f.text_field :manager_email %>
        </div>
      </div>

    <div class="control-group inline">
      <div class="controls">
        <%= f.submit "עדכן/י", class: "host_submit" %>
      </div>
    </div>

  <% end %>
</div>

app/views/cities/index.html.erb
<% title "Cities" %>

<table>
  <tr>
    <th>Name</th>
    <th>Manager</th>
  </tr>
  <% for city in @cities %>
    <tr>
      <td><%= city.name %></td>
      <td><%= city.manager_email %></td>
      <td >
        <%= link_to edit_city_path(city) do %>
        <div class="circle">
          <%= inline_svg "edit.svg" %>
        </div>
        <% end %>
      </td>
       <% if session[:auth] == "extended"  %>
        <td><%= button_to 'Delete', city, method: :delete, data: { confirm: 'אתה בטוח?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>